export {
  applyAgentLoopAssistantMessageProjection,
  assertAgentLoopTurnResponse,
  buildAgentLoopAssistantMessageProjection,
  handleAgentLoopAssistantMessage,
  runAgentLoopAssistantMessageHook,
  type AgentLoopAssistantMessageConversationLike,
  type AgentLoopAssistantMessageHookContainer,
  type AgentLoopAssistantMessageHookPayload,
  type AgentLoopAssistantMessageProjection,
  type AgentLoopAssistantMessageProjectionInput,
  type ApplyAgentLoopAssistantMessageProjectionInput,
  type HandleAgentLoopAssistantMessageInput,
  type RunAgentLoopAssistantMessageHookInput,
} from '../../../packages/agent/src/loop/assistantMessage.js';
