export {
  AGENT_LOOP_TURN_SAFETY_LIMIT,
  applyAgentLoopTurnLimitContinuation,
  buildAgentLoopTurnLimitContinuation,
  buildAgentLoopTurnLimitDecisionInput,
  buildAgentLoopTurnLimitDecisionInputFromHookContainer,
  buildAgentLoopTurnLimitDecisionInputFromLoopState,
  buildAgentLoopTurnLimitHooksInput,
  buildAgentLoopTurnLimitStopCompletion,
  buildAgentLoopEffectiveMaxTurns,
  decideTurnLimit,
  handleAgentLoopToolTurnTail,
  shouldApplyAgentLoopTurnLimitContinuation,
  shouldCheckAgentLoopTurnLimit,
  shouldStopAgentLoopForTurnLimitDecision,
  type AgentLoopToolTurnTailClockLike,
  type AgentLoopToolTurnTailEvent,
  type AgentLoopToolTurnTailHandling,
  type AgentLoopToolTurnTailTurnCounterLike,
  type ApplyAgentLoopTurnLimitContinuationInput,
  type AgentLoopApplicableTurnLimitContinuation,
  type AgentLoopTurnLimitClockLike,
  type AgentLoopTurnLimitContinuationConversationLike,
  type AgentLoopTurnLimitConversationLike,
  type AgentLoopTurnLimitDecisionHookContainerInput,
  type AgentLoopTurnLimitDecisionLoopStateInput,
  type AgentLoopTurnLimitHookContainer,
  type AgentLoopTurnLimitHooksInput,
  type AgentLoopTurnLimitContinuation,
  type AgentLoopTurnLimitStopCompletion,
  type AgentLoopTurnLimitTokenUsageTrackerLike,
  type AgentLoopTurnLimitToolResultTrackerLike,
  type BuildAgentLoopEffectiveMaxTurnsInput,
  type DecideTurnLimitInput,
  type HandleAgentLoopToolTurnTailInput,
  type ShouldCheckAgentLoopTurnLimitInput,
  type TurnLimitCompactHandler,
  type TurnLimitDecision,
  type TurnLimitReachedHandler,
  type TurnLimitResponse,
  type TurnLimitStopDecision,
  type TurnLimitStopResult,
} from '../../../packages/agent/src/loop/decideTurnLimit.js';
