export {
  AGENT_LOOP_TURN_SAFETY_LIMIT,
  buildAgentLoopTurnLimitContinuation,
  buildAgentLoopTurnLimitDecisionInput,
  buildAgentLoopTurnLimitDecisionInputFromLoopState,
  buildAgentLoopTurnLimitHooksInput,
  buildAgentLoopTurnLimitStopCompletion,
  buildAgentLoopEffectiveMaxTurns,
  decideTurnLimit,
  shouldApplyAgentLoopTurnLimitContinuation,
  shouldCheckAgentLoopTurnLimit,
  shouldStopAgentLoopForTurnLimitDecision,
  type AgentLoopApplicableTurnLimitContinuation,
  type AgentLoopTurnLimitClockLike,
  type AgentLoopTurnLimitConversationLike,
  type AgentLoopTurnLimitDecisionLoopStateInput,
  type AgentLoopTurnLimitHooksInput,
  type AgentLoopTurnLimitContinuation,
  type AgentLoopTurnLimitStopCompletion,
  type AgentLoopTurnLimitTokenUsageTrackerLike,
  type AgentLoopTurnLimitToolResultTrackerLike,
  type BuildAgentLoopEffectiveMaxTurnsInput,
  type DecideTurnLimitInput,
  type ShouldCheckAgentLoopTurnLimitInput,
  type TurnLimitCompactHandler,
  type TurnLimitDecision,
  type TurnLimitReachedHandler,
  type TurnLimitResponse,
  type TurnLimitStopDecision,
  type TurnLimitStopResult,
} from '../../../packages/agent/src/loop/decideTurnLimit.js';
