/**
 * Hook System Types
 *
 * ⚠️ MIGRATED: This file is a re-export shim.
 * The implementation now lives in @blade-ai/agent-sdk/local.
 */

export type {
  CommandHook,
  CompactionHookResult,
  CompactionInput,
  ConfigChangeHookResult,
  ConfigChangeInput,
  CwdChangedHookResult,
  CwdChangedInput,
  ElicitationHookResult,
  ElicitationInput,
  ElicitationResultHookResult,
  ElicitationResultInput,
  FileChangedHookResult,
  FileChangedInput,
  Hook,
  HookConfig,
  HookExecutionContext,
  HookExecutionResult,
  HookInput,
  HookInputBase,
  HookMatcher,
  HookOutput,
  HookSpecificOutput,
  InstructionsLoadedHookResult,
  InstructionsLoadedInput,
  MatcherConfig,
  MatchContext,
  NotificationHookResult,
  NotificationInput,
  PermissionRequestHookResult,
  PermissionRequestInput,
  PostCompactHookResult,
  PostCompactInput,
  PostToolHookResult,
  PostToolUseFailureHookResult,
  PostToolUseFailureInput,
  PostToolUseInput,
  PreCompactHookResult,
  PreCompactInput,
  PreToolHookResult,
  PreToolUseInput,
  ProcessResult,
  SessionEndHookResult,
  SessionEndInput,
  SessionStartHookResult,
  SessionStartInput,
  StopFailureHookResult,
  StopFailureInput,
  StopHookResult,
  StopInput,
  SubagentStartHookResult,
  SubagentStartInput,
  SubagentStopHookResult,
  SubagentStopInput,
  TaskCompletedHookResult,
  TaskCompletedInput,
  UserPromptSubmitHookResult,
  UserPromptSubmitInput,
} from '@blade-ai/agent-sdk/local';
export {
  DecisionBehavior,
  HookExitCode,
  HookType,
  PermissionDecision,
} from '@blade-ai/agent-sdk/local';
